apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bq3z
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bq3z
    app.kubernetes.io/part-of: ci1t-830-0072-app
  name: devfile-sample-bq3z
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bq3z
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bq3z
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0072-tenant/ci1t-830-0072-app/devfile-sample-bq3z@sha256:d4413a92dc60fea5fd6e18dff49805b16d24d08dfa65ac7c71491fd9e2044ab3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
